### ISSUE TITLE
The pg_dump version still uses v12 on release 2.6.1

### ISSUE THREAD

**Issue by kuanfandevops** [BCDevOps/backup-container#110]
Our databse is postgresql v14, the backup command failed, looks like the pg_dump is still v12 in the image.

Backing up 'zeva-spilo-test:5432/zeva' to '/backups/2023-04-21/zeva-spilo-test-zeva_2023-04-21_11-41-03.sql.gz.in_progress' ...
pg_dump: error: server version: 14.2 (Ubuntu 14.2-1.pgdg18.04+1); pg_dump version: 12.1
pg_dump: error: aborting because of server version mismatch
removed '/backups/2023-04-21/zeva-spilo-test-zeva_2023-04-21_11-41-03.sql.gz.in_progress'
[!!ERROR!!] - Failed to backup postgres=zeva-spilo-test:5432/zeva.

**Comment by WadeBarnes** [comment]
Possibly related to https://github.com/BCDevOps/backup-container/issues/109.  Is your build overriding the base image and using a redhat based image for Postgres v12?

**Comment by WadeBarnes** [comment]
I've tested the latest version on several Postgres v14 databases, both backup and restore.  In order to get the Postgres v14 features in the backup-container you need to build your images using the prescribed fedora image; https://github.com/BCDevOps/backup-container/blob/master/docker/Dockerfile#L2

**Comment by kuanfandevops** [comment]
Yes, I found it as well. Have to add BASE_IMAGE_FOR_BUILD=quay.io/fedora/postgresql-14:14 when process the build template on Openshift otherwise it will use centos12. Close the issue.
